// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import SmileOutlined from 'E:/fuu-run/fuu-run-admin/node_modules/@ant-design/icons/es/icons/SmileOutlined';
import CrownOutlined from 'E:/fuu-run/fuu-run-admin/node_modules/@ant-design/icons/es/icons/CrownOutlined';
import UserOutlined from 'E:/fuu-run/fuu-run-admin/node_modules/@ant-design/icons/es/icons/UserOutlined';
import SettingOutlined from 'E:/fuu-run/fuu-run-admin/node_modules/@ant-design/icons/es/icons/SettingOutlined';
import FileTextOutlined from 'E:/fuu-run/fuu-run-admin/node_modules/@ant-design/icons/es/icons/FileTextOutlined';
import BookOutlined from 'E:/fuu-run/fuu-run-admin/node_modules/@ant-design/icons/es/icons/BookOutlined';
import ExceptionOutlined from 'E:/fuu-run/fuu-run-admin/node_modules/@ant-design/icons/es/icons/ExceptionOutlined';
import PropertySafetyOutlined from 'E:/fuu-run/fuu-run-admin/node_modules/@ant-design/icons/es/icons/PropertySafetyOutlined';
import HomeOutlined from 'E:/fuu-run/fuu-run-admin/node_modules/@ant-design/icons/es/icons/HomeOutlined';
import StarOutlined from 'E:/fuu-run/fuu-run-admin/node_modules/@ant-design/icons/es/icons/StarOutlined';
export default { SmileOutlined, CrownOutlined, UserOutlined, SettingOutlined, FileTextOutlined, BookOutlined, ExceptionOutlined, PropertySafetyOutlined, HomeOutlined, StarOutlined };
